app = "tankmate"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = 5
swap_size_mb = 512

[experimental]
auto_rollback = true

[mounts]
source = "data"
destination = "/data"

[build]
dockerfile = "/other/Dockerfile"
ignorefile = "/other/Dockerfile.dockerignore"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
  type = "requests"
  soft_limit = 80
  hard_limit = 100

  [[http_service.checks]]
  type = "http"
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/resources/healthcheck"
  timeout = "2s"

  [[http_service.checks]]
  type = "http"
  interval = "30s"
  grace_period = "10s"
  method = "GET"
  path = "/litefs/health"
  timeout = "5s"
