import { type DosingProduct } from './types'

export const calciumProducts: DosingProduct[] = [
	// ── Brightwell ──────────────────────────────────────────────
	{
		code: 'brightwell-calcion',
		name: 'Brightwell Calcion',
		formulaType: 'liquid',
		coefficient: 40,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		warning: 'Do not exceed 10 ml per 20 gallons per day',
		sourceUrl: 'https://www.brightwellaquatics.com/products/calciont.php',
		sourceNote: '1 ml per 1 gal raises Ca by 40 ppm',
	},
	{
		code: 'brightwell-calcion-p',
		name: 'Brightwell Calcion-P',
		formulaType: 'powder',
		coefficient: 95,
		primaryUnit: 'grams',
		phEffect: 'minimal',
		warning: 'Dissolve in freshwater before adding to tank',
		sourceUrl: 'https://www.brightwellaquatics.com/products/calcionpt.php',
		sourceNote: '1 g per 1 gal raises Ca by 95 ppm',
	},
	{
		code: 'brightwell-reefcode-a',
		name: 'Brightwell ReefCode Part A',
		formulaType: 'liquid',
		coefficient: 16,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		warning: 'Dose equal parts A and B. Do not mix A and B before adding to tank',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by 16 ppm',
	},
	{
		code: 'brightwell-reefcode-a-p',
		name: 'Brightwell ReefCode Part A (Powder)',
		formulaType: 'powder',
		coefficient: 87,
		primaryUnit: 'grams',
		phEffect: 'minimal',
		warning: 'Dissolve in RO/DI water before adding. Dose equal parts A and B',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 g per 1 gal raises Ca by 87 ppm',
	},
	{
		code: 'brightwell-nanocode-a',
		name: 'Brightwell NanoCode A',
		formulaType: 'liquid',
		coefficient: 11.9,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		warning: 'Dose equal parts A and B',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by 11.9 ppm',
	},

	// ── Seachem ─────────────────────────────────────────────────
	{
		code: 'seachem-reef-advantage-calcium',
		name: 'Seachem Reef Advantage Calcium',
		formulaType: 'powder',
		coefficient: 9.6,
		primaryUnit: 'grams',
		phEffect: 'minimal',
		warning: 'Do not exceed 10 g per 40 gallons per day. Dissolve in 250 mL freshwater first',
		sourceUrl: 'https://www.seachem.com/reef-adv-calcium.php',
		sourceNote: '5 g per 40 gal raises Ca by 12 ppm (12 * 40 / 5 = 96 -> 9.6 per g per gal)',
	},
	{
		code: 'seachem-reef-complete',
		name: 'Seachem Reef Complete',
		formulaType: 'liquid',
		coefficient: 42.3,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		warning:
			'Do not exceed 12.5 mL per 20 gal per day. Do not mix directly with carbonate supplements',
		sourceUrl: 'https://www.seachem.com/reef-complete.php',
		sourceNote: 'Expert formula m=vc/160; concentration 160,000 ppm Ca (160/3.785 = 42.3)',
	},
	{
		code: 'seachem-reef-calcium',
		name: 'Seachem Reef Calcium',
		formulaType: 'liquid',
		coefficient: 1.2,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		warning: 'Polygluconate-based — best for maintenance dosing, not large corrections',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by ~1.2 ppm (organic calcium source)',
	},
	{
		code: 'seachem-fusion-1',
		name: 'Seachem Fusion Part 1',
		formulaType: 'liquid',
		coefficient: 26.42,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		warning: 'Also adds Mg, Sr, and trace elements. Dose equal parts 1 and 2',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by 26.42 ppm',
	},

	// ── ESV ──────────────────────────────────────────────────────
	{
		code: 'esv-bionic-calcium',
		name: 'ESV B-Ionic Calcium Buffer',
		formulaType: 'liquid',
		coefficient: 16,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		warning: 'Do not exceed 1 ml per gallon per day. Dose alk and Ca at least 1 hour apart',
		sourceUrl: 'https://www.esvaquarium.com/',
		sourceNote: '1 ml per 1 gal raises Ca by 16 ppm',
	},
	{
		code: 'esv-bionic-bicarbonate-2',
		name: 'ESV B-Ionic Bicarbonate System Part 2',
		formulaType: 'liquid',
		coefficient: 4,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		warning: 'Dose equal parts 1 and 2',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by 4 ppm',
	},

	// ── Red Sea ──────────────────────────────────────────────────
	{
		code: 'red-sea-foundation-a-liquid',
		name: 'Red Sea Foundation A (Liquid)',
		formulaType: 'liquid',
		coefficient: 52.8,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		sourceUrl:
			'https://g1.redseafish.com/support/product-support/products/calcium/tabs/faq/Dosing/',
		sourceNote: '1 ml per 100 L (26.42 gal) raises Ca by 2 ppm (2 * 26.42 = 52.8)',
	},
	{
		code: 'red-sea-foundation-a-powder',
		name: 'Red Sea Foundation A (Powder)',
		formulaType: 'powder',
		coefficient: 95.1,
		primaryUnit: 'grams',
		phEffect: 'minimal',
		sourceUrl:
			'https://g1.redseafish.com/support/product-support/products/calcium/tabs/faq/Dosing/',
		sourceNote: '1 g per 100 L (26.42 gal) raises Ca by 3.6 ppm (3.6 * 26.42 = 95.1)',
	},

	// ── Kent Marine ──────────────────────────────────────────────
	{
		code: 'kent-tech-cb-a',
		name: 'Kent Tech-CB Part A',
		formulaType: 'liquid',
		coefficient: 14.7,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		warning: 'Dose equal parts A and B',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by 14.7 ppm',
	},
	{
		code: 'kent-turbo-calcium',
		name: 'Kent Turbo Calcium',
		formulaType: 'powder',
		coefficient: 95.4,
		primaryUnit: 'grams',
		phEffect: 'somewhat-lower',
		warning: 'Anhydrous CaCl2 — exothermic. Dissolve in RO/DI water first. Max 50 ppm/day',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 g per 1 gal raises Ca by 95.4 ppm (anhydrous CaCl2)',
	},
	{
		code: 'kent-liquid-calcium',
		name: 'Kent Liquid Calcium',
		formulaType: 'liquid',
		coefficient: 26.42,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by 26.42 ppm',
	},

	// ── Two Little Fishies ───────────────────────────────────────
	{
		code: 'tlf-c-balance-a',
		name: 'Two Little Fishies C-Balance Part A',
		formulaType: 'liquid',
		coefficient: 10,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		warning: 'Dose equal parts A and B',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by 10 ppm',
	},

	// ── Continuum ────────────────────────────────────────────────
	{
		code: 'continuum-reef-basis-calcium',
		name: 'Continuum Reef Basis Calcium',
		formulaType: 'liquid',
		coefficient: 37,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by 37 ppm',
	},
	{
		code: 'continuum-reef-basis-calcium-p',
		name: 'Continuum Reef Basis Calcium (Powder)',
		formulaType: 'powder',
		coefficient: 90.9,
		primaryUnit: 'grams',
		phEffect: 'minimal',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 g per 1 gal raises Ca by 90.9 ppm',
	},
	{
		code: 'continuum-reef-sculpture-a',
		name: 'Continuum Reef Sculpture Part A',
		formulaType: 'liquid',
		coefficient: 15,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		warning: 'Dose equal parts A and B',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by ~15 ppm',
	},

	// ── Tropic Marin ─────────────────────────────────────────────
	{
		code: 'tropic-marin-bio-calcium',
		name: 'Tropic Marin Bio-Calcium',
		formulaType: 'powder',
		coefficient: 40,
		primaryUnit: 'grams',
		phEffect: 'somewhat-higher',
		warning:
			'Also raises alkalinity by ~4 dKH per 7 g per 10 gal. Do not exceed 440 ppm Ca',
		sourceUrl: 'https://www.tropic-marin-smartinfo.com/bio-calcium?lang=en',
		sourceNote: '1 scoop (~7 g) per 10 gal raises Ca by 28 ppm (28 * 10 / 7 = 40)',
	},

	// ── Salifert ─────────────────────────────────────────────────
	{
		code: 'salifert-coral-calcium',
		name: 'Salifert Coral Calcium',
		formulaType: 'liquid',
		coefficient: 42.3,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		warning: 'Never increase calcium by more than 50 ppm per day',
		sourceUrl: 'http://www.salifert.com/sup/cc.htm',
		sourceNote: '5 ml per 100 L (26.42 gal) raises Ca by 8 ppm (8 * 26.42 / 5 = 42.3)',
	},
	{
		code: 'salifert-all-in-one-ca',
		name: 'Salifert All in One (Calcium)',
		formulaType: 'liquid',
		coefficient: 13.2,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		warning: 'Maintenance only — not for large corrections',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by 13.2 ppm',
	},

	// ── Warner Marine ────────────────────────────────────────────
	{
		code: 'warner-calxmax-a',
		name: 'Warner Marine CalxMax Part A',
		formulaType: 'liquid',
		coefficient: 15,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		warning: 'Dose equal parts A and B',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by 15 ppm',
	},
	{
		code: 'warner-reefpure-calcium',
		name: 'Warner Marine ReefPure Calcium',
		formulaType: 'liquid',
		coefficient: 35,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by 35 ppm',
	},

	// ── Aquaforest ───────────────────────────────────────────────
	{
		code: 'aquaforest-calcium-p',
		name: 'Aquaforest Calcium (Powder)',
		formulaType: 'powder',
		coefficient: 92.45,
		primaryUnit: 'grams',
		phEffect: 'minimal',
		warning: 'Dissolve in RO/DI water before adding',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 g per 1 gal raises Ca by 92.45 ppm',
	},
	{
		code: 'aquaforest-ca-plus',
		name: 'Aquaforest Ca Plus',
		formulaType: 'liquid',
		coefficient: 26.42,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by 26.42 ppm',
	},

	// ── Randy Holmes-Farley DIY ──────────────────────────────────
	{
		code: 'randys-recipe-1-ca',
		name: "Randy's Recipe #1 (Calcium)",
		formulaType: 'liquid',
		coefficient: 9.77,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		warning: 'DIY solution — 73.6 g CaCl2·2H2O per 1 L RO/DI water',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by 9.77 ppm',
	},
	{
		code: 'randys-recipe-2-ca',
		name: "Randy's Recipe #2 (Calcium)",
		formulaType: 'liquid',
		coefficient: 4.9,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		warning: 'DIY solution — 36.8 g CaCl2·2H2O per 1 L RO/DI water',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by 4.9 ppm',
	},

	// ── Fritz ────────────────────────────────────────────────────
	{
		code: 'fritz-anhydrous-cacl2',
		name: 'Fritz ProAquatics Anhydrous CaCl2',
		formulaType: 'powder',
		coefficient: 95.4,
		primaryUnit: 'grams',
		phEffect: 'somewhat-lower',
		warning: 'Exothermic — dissolve in RO/DI water first. Max 50 ppm/day',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 g per 1 gal raises Ca by 95.4 ppm (anhydrous CaCl2)',
	},

	// ── MEcoral ──────────────────────────────────────────────────
	{
		code: 'mecoral-calcium',
		name: 'MEcoral Calcium',
		formulaType: 'liquid',
		coefficient: 10,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by 10 ppm',
	},

	// ── Oceans Blend ─────────────────────────────────────────────
	{
		code: 'oceans-blend-part-1',
		name: 'Oceans Blend Part 1',
		formulaType: 'liquid',
		coefficient: 10,
		primaryUnit: 'ml',
		phEffect: 'minimal',
		warning: 'Also contains magnesium',
		sourceUrl: 'https://reef.diesyst.com/chemcalc/chemcalc.html',
		sourceNote: '1 ml per 1 gal raises Ca by 10 ppm',
	},

	// ── Generic / DIY ────────────────────────────────────────────
	{
		code: 'calcium-chloride',
		name: 'Calcium Chloride (CaCl2·2H2O)',
		formulaType: 'powder',
		coefficient: 72,
		primaryUnit: 'grams',
		phEffect: 'somewhat-lower',
		warning:
			'Exothermic — dissolve in RO/DI water first. Can deplete alkalinity. Max 50 ppm/day',
		sourceUrl:
			'https://www.bulkreefsupply.com/content/post/brs-pharma-calcium-chloride-mixing-and-dosing-instructions',
		sourceNote:
			'Stoichiometric: MW 147.01, Ca fraction 27.26%. 1 g per 3.785 L = 272.6 mg / 3.785 L = 72 ppm',
	},
	{
		code: 'kalkwasser',
		name: 'Kalkwasser (Saturated Ca(OH)2)',
		formulaType: 'limewater',
		coefficient: 0.254,
		primaryUnit: 'ml',
		phEffect: 'substantially-higher',
		warning:
			'pH ~12.4 — add very slowly via ATO only. Cannot raise Ca rapidly due to low solubility. Also raises alkalinity',
		sourceUrl:
			'https://www.bulkreefsupply.com/content/post/using-kalkwasser',
		sourceNote:
			'1 gal (3785 ml) saturated solution per 40 gal tank raises Ca by 24 ppm (24 * 40 / 3785 = 0.254)',
	},
]
